# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

- id: doi:10.1145/3737894
  image: images/paper_pecan.png
  tags:
    - human interaction
    - robot learning

- id: doi:10.48550/arXiv.2505.12072
  image: images/photo.jpg

- id: doi:10.48550/arXiv.2504.17959
  image: images/photo.jpg

- id: doi:10.48550/arXiv.2501.01323
  image: images/photo.jpg

- id: doi:10.48550/arXiv.2409.13607
  image: images/photo.jpg

- id: doi:10.1109/LRA.2024.3415432
  image: images/paper_selecting2023

- title: 'Fair Contextual Multi-Armed Bandits: Theory and Experiments'
  authors:
  - Yifang Chen
  - Alex Cuellar
  - Haipeng Luo
  - Jignesh Modi
  - Heramb Nemlekar
  - Stefanos Nikolaidis
  publisher: Conference on Uncertainty in Artificial Intelligence
  date: 2020-08-27