# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

- id: doi:10.48550/arXiv.2508.06319
  image: images/paper_balanced2026.png
  tags:
    - robot learning

- id: doi:10.48550/arXiv.2504.17959
  image: images/paper_civil2026.png
  tags:
    - robot learning

- id: doi:10.48550/arXiv.2501.01323
  image: images/thread_design.png
  tags:
    - mechanism design
    - human interaction

- id: doi:10.48550/arXiv.2409.13607
  image: images/paper_recon2025.png
  tags:
    - robot learning

- id: doi:10.1145/3737894
  image: images/paper_pecan2025.png
  tags:
    - human interaction
    - robot learning

- id: doi:10.1007/s10514-025-10210-x
  image: images/paper_l2d22025.png
  tags:
    - robot learning

- id: doi:10.1109/icra55743.2025.11128246
  image: images/paper_ben2025.png
  tags:
    - human interaction
    - robot learning

- id: doi:10.1109/TASE.2025.3546281
  image: images/paper_contingency2025.jpg
  tags:
    - multi-agent coordination
    - planning

- id: doi:10.1109/iros58592.2024.10801346
  image: images/paper_kiri2024.png
  tags:
    - mechanism design
    - human interaction

- id: doi:10.1109/icra57147.2024.10611370
  image: images/paper_neel2024.png
  tags:
    - multi-agent coordination
    - planning

- id: doi:10.48550/arXiv.2304.13787
  image: images/paper_surrogate2023.png
  tags:
    - robot learning

- id: doi:10.1109/LRA.2024.3415432
  image: images/paper_selecting2023.png
  tags:
    - robot learning

- id: doi:10.1145/3568162.3576965
  image: images/paper_transfer2023.png
  tags:
    - robot learning
    - human interaction

- id: doi:10.1109/ro-man53752.2022.9900551
  image: images/paper_assignment2022.png
  tags:
    - multi-agent coordination
    - human interaction

- id: doi:10.1109/ro-man53752.2022.9900872
  image: images/paper_canonical2022.jpg
  tags: 
    - human interaction

- id: doi:10.1109/iros51168.2021.9636396
  image: images/thread_motion.png
  tags: 
    - planning

- id: doi:10.1109/icra48506.2021.9561649
  image: images/paper_clustering2021.jpg
  tags:
    - robot learning
    - human interaction

- title: 'Fair Contextual Multi-Armed Bandits: Theory and Experiments'
  authors:
  - Yifang Chen
  - Alex Cuellar
  - Haipeng Luo
  - Jignesh Modi
  - Heramb Nemlekar
  - Stefanos Nikolaidis
  publisher: Conference on Uncertainty in Artificial Intelligence
  date: 2020-08-27
  image: images/thread_multi.png
  tags:
    - multi-agent coordination
    - human interaction

- id: doi:10.1109/icra.2019.8794008
  image: images/paper_handover2019.png
  tags:
    - human interaction